# Generated by Django 5.2.15 on 2026-07-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermissaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('access_dashboard', 'Pode acessar o dashboard'), ('view_auditoria', 'Pode visualizar auditoria'), ('export_data', 'Pode exportar dados')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
