# Generated by Django 5.2.15 on 2026-07-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Separacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('romaneio', models.CharField(max_length=50, verbose_name='Romaneio')),
                ('documento', models.CharField(max_length=80, verbose_name='Documento')),
                ('grupo', models.CharField(max_length=80, verbose_name='Grupo')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('vencimento', models.DateField(blank=True, null=True, verbose_name='Vencimento')),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('prioritaria', 'Prioritaria'), ('urgente', 'Urgente')], default='normal', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluida'), ('cancelada', 'Cancelada')], default='aberta', max_length=20, verbose_name='Status')),
                ('quantidade_pendente', models.PositiveIntegerField(default=0, verbose_name='Quantidade pendente')),
                ('status_operacional', models.CharField(choices=[('pendente', 'Pendente'), ('em_separacao', 'Em separacao'), ('conferida', 'Conferida'), ('finalizada', 'Finalizada')], default='pendente', max_length=30, verbose_name='Status operacional')),
                ('status_documento', models.CharField(choices=[('valido', 'Valido'), ('divergente', 'Divergente'), ('bloqueado', 'Bloqueado')], default='valido', max_length=20, verbose_name='Status do documento')),
                ('quantidade_conferida', models.PositiveIntegerField(default=0, verbose_name='Quantidade conferida')),
                ('status_autorizacao', models.CharField(choices=[('pendente', 'Pendente'), ('autorizado', 'Autorizado'), ('negado', 'Negado')], default='pendente', max_length=20, verbose_name='Status da autorizacao')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Separacao',
                'verbose_name_plural': 'Separacoes',
                'ordering': ['-data', 'romaneio', 'documento'],
                'permissions': [('access_separacao', 'Pode acessar o modulo separacao')],
            },
        ),
    ]
