# Generated by Django 5.2.15 on 2026-07-02 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('separacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='separacao',
            options={'ordering': ['-data', 'romaneio', 'documento'], 'permissions': [('access_separacao', 'Pode acessar o modulo separacao'), ('create_record', 'Pode criar registro'), ('edit_record', 'Pode editar registro'), ('delete_record', 'Pode excluir registro')], 'verbose_name': 'Separacao', 'verbose_name_plural': 'Separacoes'},
        ),
    ]
