# Generated by Django 5.2.15 on 2026-07-02 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('separacao', '0002_alter_separacao_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='separacao',
            name='anotacoes',
            field=models.TextField(blank=True, verbose_name='Anotacoes'),
        ),
        migrations.AddField(
            model_name='separacao',
            name='atribuido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separacoes_atribuidas', to=settings.AUTH_USER_MODEL, verbose_name='Atribuido'),
        ),
    ]
