# Generated by Django 5.2.15 on 2026-07-02 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criacao', 'Criacao'), ('edicao', 'Edicao'), ('exclusao', 'Exclusao')], max_length=20, verbose_name='Acao')),
                ('app', models.CharField(max_length=80, verbose_name='App')),
                ('modelo', models.CharField(max_length=80, verbose_name='Modelo')),
                ('objeto_id', models.CharField(max_length=64, verbose_name='ID do objeto')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descricao')),
                ('dados', models.JSONField(blank=True, default=dict, verbose_name='Dados')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Evento de auditoria',
                'verbose_name_plural': 'Eventos de auditoria',
                'ordering': ['-criado_em'],
            },
        ),
    ]
